apiVersion: v1
kind: ConfigMap
metadata:
  name: wizly-supportbot-config
  namespace: {{ .Release.Namespace }}
data:
{{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
