apiVersion: v1
kind: Service
metadata:
  name: wizly-supportbot
  namespace: {{ .Release.Namespace }}
  labels:
    app: wizly-supportbot
spec:
  type: ClusterIP
  selector:
    app: wizly-supportbot
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
