image:
  repository: "superfyutilsacr.azurecr.io/wizly-supportbot"
  tag: "initial"
  pullPolicy: Always

replicaCount: 1

config:
  NODE_ENV: "production"
  DATA_DIR: "/app/data"
  APP_URL: "https://wyzly-support.tacobrain.online"

ingress:
  className: "webapprouting.kubernetes.azure.com"
  host: "wyzly-support.tacobrain.online"
  clusterIssuer: "letsencrypt"

persistence:
  enabled: true
  size: 1Gi
  storageClass: ""
  accessMode: ReadWriteOnce

resources:
  requests:
    cpu: "100m"
    memory: "256Mi"
  limits:
    cpu: "500m"
    memory: "512Mi"
